openapi: 3.0.3
info:
  title: VoteCryp Results Service API
  version: 1.0.0
  description: Servicio para descifrar y exponer resultados agregados (mock).
servers:
  - url: http://localhost:4003
paths:
  /health:
    get:
      summary: Health
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok:
                    type: boolean
                    example: true
  /decryptResults:
    post:
      summary: Descifrar resultados
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [encryptedResults]
              properties:
                encryptedResults:
                  type: array
                  items:
                    type: string
      responses:
        '200':
          description: Resultados descifrados
          content:
            application/json:
              schema:
                type: object
                properties:
                  decryptedResults:
                    type: array
                    items:
                      type: integer
                  success:
                    type: boolean
        '400':
          description: Invalid body
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
